{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "c0303c34",
   "metadata": {},
   "source": [
    "# <center>Bangla Handwritten Math Solver (GUI)<center> "
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6ec735f6",
   "metadata": {},
   "source": [
    "## Importing Libraries "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "6d607711",
   "metadata": {},
   "outputs": [],
   "source": [
    "from keras.models import load_model\n",
    "from tkinter import *\n",
    "from tkinter.ttk import *\n",
    "from PIL import ImageGrab\n",
    "import cv2\n",
    "import imutils\n",
    "from imutils.contours import sort_contours\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7610fe6b",
   "metadata": {},
   "source": [
    "## Initializing Canvas"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "8617fea1",
   "metadata": {},
   "outputs": [],
   "source": [
    "res = \"\"\n",
    "pre = [None, None]\n",
    "bs = 5.5\n",
    "\n",
    "root = Tk()\n",
    "root.title(\"Bangla Handwriting Math Solver\")\n",
    "root.resizable(False, False)\n",
    "# root.overrideredirect(True) # turns off title bar\n",
    "\n",
    "# root size we want to create\n",
    "root_height = 600\n",
    "root_width = 1024\n",
    "\n",
    "# getting the full screen height and width\n",
    "screen_width = root.winfo_screenwidth()\n",
    "screen_height = root.winfo_screenheight()\n",
    "\n",
    "# calculating the geometry padding\n",
    "x_cordinate = int((screen_width/2) - (root_width/2))\n",
    "y_cordinate = int((screen_height/2) - (root_height/2))\n",
    "\n",
    "# canvas size \n",
    "canvas_width = root_width - 52\n",
    "canvas_height = root_height - 150\n",
    "\n",
    "root.geometry(\"{}x{}+{}+{}\".format(root_width, root_height, x_cordinate, y_cordinate))\n",
    "c = Canvas(root, bd=3, relief=\"ridge\", bg='white', height=canvas_height, width=canvas_width)\n",
    "c.grid(row=0, column=0, columnspan=3, padx=20, pady=10)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b57f1f45",
   "metadata": {},
   "source": [
    "## Function for closing window"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "2c089647",
   "metadata": {},
   "outputs": [],
   "source": [
    "def close():\n",
    "    root.destroy()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "830f5803",
   "metadata": {},
   "source": [
    "## Function for clearing the canvas"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "ef560d71",
   "metadata": {},
   "outputs": [],
   "source": [
    "def clear():\n",
    "    c.delete(\"all\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "312b3aff",
   "metadata": {},
   "source": [
    "## Function for putting a point on the canvas"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "04d15b31",
   "metadata": {},
   "outputs": [],
   "source": [
    "def putPoint(e):\n",
    "    c.create_oval(e.x - bs, e.y - bs, e.x + bs, e.y + bs, outline='black', fill='black')\n",
    "    pre = [e.x, e.y]"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "52d50f9f",
   "metadata": {},
   "source": [
    "## Function for drawing on the canvas"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "d0a802f0",
   "metadata": {},
   "outputs": [],
   "source": [
    "def paint(e):\n",
    "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
    "    pre = [e.x, e.y]"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "42fab0a1",
   "metadata": {},
   "source": [
    "## Function for getting the image from the canvas"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "5a014699",
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_image():\n",
    "    print('Processing image from the canvas...')\n",
    "    label['text'] = 'Processing image from the canvas...'\n",
    "    #\n",
    "    x, y = (c.winfo_rootx(), c.winfo_rooty())\n",
    "    width, height = (c.winfo_width(), c.winfo_height())\n",
    "    a, b, c, d = (x, y, x+width, y+height)\n",
    "    #\n",
    "    img = ImageGrab.grab()\n",
    "    img.save(\"output/1_full-screen.png\")\n",
    "    img = img.crop((a + 76, b + 48, c + 313, d + 154))\n",
    "    img.save(\"output/2_drawn-image.png\")\n",
    "    print('Image saved!')\n",
    "    label['text'] = 'Image saved!'\n",
    "    return True"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1e709e0d",
   "metadata": {},
   "source": [
    "## Functions for getting the equation and solve"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "adf6d514",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Function for solving the prediction\n",
    "def get_equation_and_solve():\n",
    "    print('Solving the equation...')\n",
    "    label['text'] = 'Loading the model...'\n",
    "    model = load_model('math_symbol_and_digit_recognition.h5')\n",
    "    chars = []\n",
    "    img = cv2.imread('output/2_drawn-image.png')\n",
    "    img = cv2.resize(img, (canvas_width, canvas_height))\n",
    "    img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)\n",
    "    edged = cv2.Canny(img_gray, 30, 150)\n",
    "    contours = cv2.findContours(edged.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)\n",
    "    contours = imutils.grab_contours(contours)\n",
    "    print('Number of contours found: ', len(contours))\n",
    "    contours = sort_contours(contours, method=\"left-to-right\")[0]\n",
    "    labels = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'add', 'div', 'mul', 'sub']\n",
    "\n",
    "    for i, c in enumerate(contours):\n",
    "        print('Processing the image...: ', str(i+1))\n",
    "        (x, y, w, h) = cv2.boundingRect(c)\n",
    "        print('x: ', x, 'y: ', y, 'w: ', w, 'h: ', h)\n",
    "        # if x > 0 and y > 0 and w >= 5 and h >= 25:\n",
    "        if x > 0 and y > 0 and w > 5:  # cheaking weather any garbage value detecting\n",
    "            roi = img_gray[y:y+h, x:x+w]\n",
    "            thresh = cv2.threshold(roi, 0, 255, cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)[1]\n",
    "            (th, tw) = thresh.shape\n",
    "            if tw > th:\n",
    "                thresh = imutils.resize(thresh, width=32)\n",
    "            if th > tw:\n",
    "                thresh = imutils.resize(thresh, height=32)\n",
    "            (th, tw) = thresh.shape\n",
    "            dx = int(max(0, 32 - tw)/2.0)\n",
    "            dy = int(max(0, 32 - th) / 2.0)\n",
    "            padded = cv2.copyMakeBorder(thresh, top=dy, bottom=dy, left=dx, right=dx, borderType=cv2.BORDER_CONSTANT, value=(0, 0, 0))\n",
    "            padded = cv2.resize(padded, (32, 32))\n",
    "            padded = np.array(padded)\n",
    "            padded = padded/255.\n",
    "            padded = np.expand_dims(padded, axis=0)\n",
    "            padded = np.expand_dims(padded, axis=-1)\n",
    "            pred = model.predict(padded)\n",
    "            pred = np.argmax(pred, axis=1)\n",
    "            label = labels[pred[0]]\n",
    "            print('>>>>The {} no word is : {}'.format(i, label))\n",
    "            chars.append(label)\n",
    "            cv2.rectangle(img, (x, y), (x+w, y+h), (0, 0, 255), 2)\n",
    "            cv2.putText(img, label, (x-5, y), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255))\n",
    "\n",
    "    plt.figure(figsize=(10, 10))\n",
    "    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)\n",
    "    plt.imshow(img)\n",
    "    plt.axis('off')\n",
    "    plt.savefig('output/3_system_prediction.png')\n",
    "\n",
    "    e = ''\n",
    "    print('Equation: {}', chars)\n",
    "    for i in chars:\n",
    "        if i=='add':\n",
    "            e += '+'\n",
    "        elif i=='sub':\n",
    "            e += '-'\n",
    "        elif i=='mul':\n",
    "            e += '*'\n",
    "        elif i=='div':\n",
    "            e += '/'\n",
    "        else:\n",
    "            e += i\n",
    "    v = eval(e)\n",
    "    print('V Result: {}', v)\n",
    "    print('E Result: {}', e)\n",
    "\n",
    "    self.label['text'] = 'The result is: {} : {}'.format(e, v) \n",
    "    print('Value of the expression {} : {}'.format(e, v))\n",
    "    pass"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d90fd955",
   "metadata": {},
   "source": [
    "## Functions for proccessing image and equation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4b3bfa7d",
   "metadata": {},
   "outputs": [],
   "source": [
    "def solve():\n",
    "    print('Starting the work...')\n",
    "    success = get_image()\n",
    "    if success:\n",
    "        get_equation_and_solve()\n",
    "    else:\n",
    "        print(\"Error in fetching image!\")\n",
    "        label['text'] = 'Error in fetching image!'"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "aedbc3f7",
   "metadata": {},
   "source": [
    "## Functions for config canvas"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "36968e76",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create label\n",
    "label = Label(root, text = \"Draw your mathematical term here...ðŸ‘†ðŸ‘†\", )\n",
    "label.config(font =(\"Courier\", 14))\n",
    "label.grid(row=1, column=0, columnspan=3)\n",
    "\n",
    "# Create label blank for spacing\n",
    "space = Label(root, text = \"\", )\n",
    "space.config(font =(\"Courier\", 14))\n",
    "space.grid(row=2, column=0, columnspan=3)\n",
    "\n",
    "style = Style()\n",
    "\n",
    "''' Button 1: Exit'''\n",
    "style.configure('E.TButton', font = ('calibri', 15, 'bold', 'underline'), foreground = 'red')\n",
    "exit_btn = Button(root, text = 'Quit !', style = 'E.TButton', command = close)\n",
    "exit_btn.grid(row = 3, column = 0)\n",
    "\n",
    "''' Button 2: Clear'''\n",
    "style.configure('C.TButton', font = ('calibri', 15, 'bold', 'underline'), foreground = 'blue')\n",
    "calculate_btn = Button(root, text = 'Clear', style = 'C.TButton', command = clear)\n",
    "calculate_btn.grid(row = 3, column = 1)\n",
    "\n",
    "''' Button 3: Solve'''\n",
    "style.configure('S.TButton', font = ('calibri', 15, 'bold', 'underline'), foreground = 'green')\n",
    "exit_btn = Button(root, text = 'Solve', style = 'S.TButton', command = solve)\n",
    "exit_btn.grid(row = 3, column = 2)\n",
    "\n",
    "c.bind(\"<Button-1>\", putPoint)\n",
    "# c.bind(\"<ButtonRelease-1>\", getResult)\n",
    "c.bind(\"<B1-Motion>\", paint)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d9f127b5",
   "metadata": {},
   "source": [
    "## Executing function"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "6d981890",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sabik\\AppData\\Local\\Temp\\ipykernel_12876\\1510092135.py\", line 2, in paint\n",
      "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
      "UnboundLocalError: local variable 'pre' referenced before assignment\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[1;32mIn [12], line 1\u001b[0m\n\u001b[1;32m----> 1\u001b[0m \u001b[43mroot\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mmainloop\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32mc:\\users\\sabik\\appdata\\local\\programs\\python\\python38\\lib\\tkinter\\__init__.py:1420\u001b[0m, in \u001b[0;36mMisc.mainloop\u001b[1;34m(self, n)\u001b[0m\n\u001b[0;32m   1418\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mmainloop\u001b[39m(\u001b[38;5;28mself\u001b[39m, n\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m0\u001b[39m):\n\u001b[0;32m   1419\u001b[0m     \u001b[38;5;124;03m\"\"\"Call the mainloop of Tk.\"\"\"\u001b[39;00m\n\u001b[1;32m-> 1420\u001b[0m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mtk\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mmainloop\u001b[49m\u001b[43m(\u001b[49m\u001b[43mn\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f96e7e1e",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "95003a02",
   "metadata": {},
   "source": [
    "# <center>Bangla Handwritten Math Solver (GUI)<center> "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "35a92420",
   "metadata": {},
   "outputs": [],
   "source": [
    "from tkinter import *\n",
    "from tkinter.ttk import *\n",
    "from PIL import ImageGrab"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "42ebf2b5",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'close' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[1;32mIn [2], line 40\u001b[0m\n\u001b[0;32m     38\u001b[0m \u001b[38;5;124;03m''' Button 1: Exit'''\u001b[39;00m\n\u001b[0;32m     39\u001b[0m style\u001b[38;5;241m.\u001b[39mconfigure(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mE.TButton\u001b[39m\u001b[38;5;124m'\u001b[39m, font \u001b[38;5;241m=\u001b[39m (\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mcalibri\u001b[39m\u001b[38;5;124m'\u001b[39m, \u001b[38;5;241m15\u001b[39m, \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mbold\u001b[39m\u001b[38;5;124m'\u001b[39m, \u001b[38;5;124m'\u001b[39m\u001b[38;5;124munderline\u001b[39m\u001b[38;5;124m'\u001b[39m), foreground \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mred\u001b[39m\u001b[38;5;124m'\u001b[39m)\n\u001b[1;32m---> 40\u001b[0m exit_btn \u001b[38;5;241m=\u001b[39m Button(root, text \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mQuit !\u001b[39m\u001b[38;5;124m'\u001b[39m, style \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mE.TButton\u001b[39m\u001b[38;5;124m'\u001b[39m, command \u001b[38;5;241m=\u001b[39m \u001b[43mclose\u001b[49m)\n\u001b[0;32m     41\u001b[0m exit_btn\u001b[38;5;241m.\u001b[39mgrid(row \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m3\u001b[39m, column \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m0\u001b[39m)\n\u001b[0;32m     43\u001b[0m \u001b[38;5;124;03m''' Button 2: Clear'''\u001b[39;00m\n",
      "\u001b[1;31mNameError\u001b[0m: name 'close' is not defined"
     ]
    }
   ],
   "source": [
    "res = \"\"\n",
    "pre = [None, None]\n",
    "bs = 5.5\n",
    "\n",
    "root = Tk()\n",
    "root.title(\"Bangla Handwriting Math Solver\")\n",
    "root.resizable(False, False)\n",
    "# root.overrideredirect(True) # turns off title bar\n",
    "\n",
    "# root size we want to create\n",
    "root_height = 600\n",
    "root_width = 1024\n",
    "\n",
    "# getting the full screen height and width\n",
    "screen_width = root.winfo_screenwidth()\n",
    "screen_height = root.winfo_screenheight()\n",
    "\n",
    "# calculating the geometry padding\n",
    "x_cordinate = int((screen_width/2) - (root_width/2))\n",
    "y_cordinate = int((screen_height/2) - (root_height/2))\n",
    "\n",
    "root.geometry(\"{}x{}+{}+{}\".format(root_width, root_height, x_cordinate, y_cordinate))\n",
    "c = Canvas(root, bd=3, relief=\"ridge\", bg='white', height=root_height - 150, width=root_width - 52)\n",
    "c.grid(row=0, column=0, columnspan=3, padx=20, pady=10)\n",
    "\n",
    "# Create label\n",
    "label = Label(root, text = \"Draw your mathematical term here...ðŸ‘†ðŸ‘†\", )\n",
    "label.config(font =(\"Courier\", 14))\n",
    "label.grid(row=1, column=0, columnspan=3)\n",
    "\n",
    "# Create label blank for spacing\n",
    "space = Label(root, text = \"\", )\n",
    "space.config(font =(\"Courier\", 14))\n",
    "space.grid(row=2, column=0, columnspan=3)\n",
    "\n",
    "style = Style()\n",
    "\n",
    "''' Button 1: Exit'''\n",
    "style.configure('E.TButton', font = ('calibri', 15, 'bold', 'underline'), foreground = 'red')\n",
    "exit_btn = Button(root, text = 'Quit !', style = 'E.TButton', command = close)\n",
    "exit_btn.grid(row = 3, column = 0)\n",
    "\n",
    "''' Button 2: Clear'''\n",
    "style.configure('C.TButton', font = ('calibri', 15, 'bold', 'underline'), foreground = 'blue')\n",
    "calculate_btn = Button(root, text = 'Clear', style = 'C.TButton', command = clear)\n",
    "calculate_btn.grid(row = 3, column = 1)\n",
    "\n",
    "''' Button 3: Solve'''\n",
    "style.configure('S.TButton', font = ('calibri', 15, 'bold', 'underline'), foreground = 'green')\n",
    "exit_btn = Button(root, text = 'Solve', style = 'S.TButton', command = solve)\n",
    "exit_btn.grid(row = 3, column = 2)\n",
    "\n",
    "c.bind(\"<Button-1>\", putPoint)\n",
    "# c.bind(\"<ButtonRelease-1>\", getResult)\n",
    "c.bind(\"<B1-Motion>\", paint)\n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0d7d8545",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Function for closing window\n",
    "def close():\n",
    "    root.destroy()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1aad0981",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Function for clearing the canvas\n",
    "def clear():\n",
    "    c.delete(\"all\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "45b9c33f",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Function for putting a point on the canvas\n",
    "def putPoint(e):\n",
    "    c.create_oval(e.x - bs, e.y - bs, e.x + bs, e.y + bs, outline='black', fill='black')\n",
    "    pre = [e.x, e.y]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "07df0b30",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Function for drawing on the canvas\n",
    "def paint(e):\n",
    "    c.create_line(pre[0], pre[1], e.x, e.y, width=bs * 2, fill='black', capstyle=ROUND, smooth=TRUE)\n",
    "    pre = [e.x, e.y]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "505de566",
   "metadata": {},
   "outputs": [],
   "source": [
    "def solve():\n",
    "    print('Starting the work...')\n",
    "    success = get_image()\n",
    "    if success:\n",
    "        get_solve()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2d4a8611",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Function for getting the image from the canvas\n",
    "def get_image():\n",
    "    print('Processing image from the canvas...')\n",
    "    #\n",
    "    x, y = (c.winfo_rootx(), c.winfo_rooty())\n",
    "    width, height = (c.winfo_width(), c.winfo_height())\n",
    "    a, b, c, d = (x, y, x+width, y+height)\n",
    "    #\n",
    "    img = ImageGrab.grab()\n",
    "    img.save(\"full-screen.png\")\n",
    "    img = img.crop((a + 76, b + 48, c + 313, d + 154))\n",
    "    img.save(\"drawn-image.png\")\n",
    "    print('Image saved!')\n",
    "    return True"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3aaf8748",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Function for solving the prediction\n",
    "def get_solve():\n",
    "    print('Solving the equation...')\n",
    "    pass"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7735de44",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Executing function\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e339d2fd",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
